reviews/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /
    url(r'^$', views.review_list, name='review_list'),
    # ex: /review/5/
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    # ex: /wine/
    url(r'^wine$', views.wine_list, name='wine_list'),
    # ex: /wine/5/
    url(r'^wine/(?P<wine_id>[0-9]+)/$', views.wine_detail, name='wine_detail'),
]

winerama/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^reviews/', include('reviews.urls', namespace="reviews")),
    url(r'^admin/', include(admin.site.urls)),
]

reviews/models.py
from django.db import models
import numpy as np


class Wine(models.Model):
    name = models.CharField(max_length=200)

    def average_rating(self):
        all_ratings = map(lambda x: x.rating, self.review_set.all())
        return np.mean(all_ratings)

    def __str__(self):
        return self.name


class Review(models.Model):
    RATING_CHOICE = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )

    wine = models.ForeignKey(Wine)
    pub_date = models.DateTimeField('date_published')
    user_name = models.CharField(max_length=200)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICE)

reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }

reviews/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from .forms import ReviewForm
from .models import Review, Wine

import datetime

from django.contrib.auth.decorators import login_required

# Create your views here.


def review_list(request):
    latest_review_list = Review.objects.order_by('pub_date')[:9]
    context = {'latest_review_list':latest_review_list}
    return render(request,'reviews/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})


def wine_list(request):
    wine_list = Wine.objects.order_by('-name')
    context = {'wine_list': wine_list}
    return render(request, 'reviews/wine_list.html', context)


def wine_detail(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    return render(request, 'reviews/wine_detail.html', {'wine': wine})

@login_required
def add_review(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        user_name = request.user.username
        review = Review()
        review.wine = wine
        review.user_name = user_name
        review.rating = rating
        review.comment = comment
        review.pub_date = datetime.datetime.now()
        review.save()
        update_clusters()
        return HttpResponseRedirect(reverse('reviews:wine_detail', args=(wine.id,)))

    return render(request, 'reviews/wine_detail.html',{'wine':wine, 'form': form})

reviews/templates/reviews/review_detail.html
<h2><a href="{% url 'reviews:wine_detail' review.wine.id %}">{{ review.wine.name }}</a></h2>

<h4>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>

reviews/templates/reviews/review_list.html
<h2>latest_review</h2>


{% if latest_review_list %}
<div>
    {% for review in latest_review_list %}
    <div>
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
            {{ review.wine.name }}
        </a></h4>
        <h6> rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}

</div>
    {% else %}
    <p>No reviews are available</p>
{% endif %}

reviews/templates/reviews/wine_detail.html
<h2>{{ wine.name }}</h2>
<h5>{{ wine.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>


<h3>Recent reviews</h3>

{% if wine.review_set.all %}
<div>
    {% for review in wine.review_set.all %}
    <div>
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this wine yet</p>
{% endif %}
{#<h3>Add your review</h3>#}
{#{% if error_message %}#}
{#<p><strong>{{ error_mesage }}</strong></p>#}
{#{% endif %}#}
{##}
{#<form action="{% url 'reviews:add_review' wine.id %}" method="post">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <input type="submit" value="Add" />#}
{#</form>#}

reviews/templates/reviews/wine_list.html
<h2>Wine list</h2>

{% if wine_list %}
<div>
    {% for wine in wine_list %}
    <div>
        <h4><a href="{% url 'reviews:wine_detail' wine.id %}">
            {{ wine.name }}
        </a></h4>
        <h5>{{ wine.review_set.count }} reviews</h5>
        <h5>{{ wine.average_rating | floatformat }} average rating</h5>
    </div>
    {% endfor %}
</div>
    {% else %}
    <p>No wines are available.</p>
{% endif %}